### PR TITLE
add Makefile, .gitignore

### PR DESCRIPTION
**Pull request by FadeMind**
@oberon2007  ;)

### CODE REVIEW

**Comment by FadeMind** [comment]
Simplify package function for https://github.com/manjaro/packages-extra/tree/master/manjaro-wallpapers-17.0

```
package() {
    make -C "${pkgname}" install DESTDIR="$pkgdir"
}
```

@oberon2007

**Comment by oberon2007** [comment]
Thanks @FadeMind :smiling_imp:

**Comment by FadeMind** [comment]
@oberon2007  Carefull in `make -C "${pkgname}"` - set proper C :P

**Comment by oberon2007** [comment]
What do you mean? I just did
```
package() {
    cd $pkgname-$pkgver
    make install DESTDIR="$pkgdir"
}
```
and works fine. ;)

**Comment by oberon2007** [comment]
ah, you mean the build() ?

**Comment by FadeMind** [comment]
```
package() {
    make -C "${pkgname}-${pkgver}" install DESTDIR="$pkgdir"
}
```
do the job too

**Comment by oberon2007** [comment]
yes, sure. It's the same :wink:

**Comment by oberon2007** [comment]
nice though :smiley_cat:

**Comment by oberon2007** [comment]
It's strange to have a PKGBUILD wider than long ... :confused: :stuck_out_tongue_winking_eye:

**Comment by FadeMind** [comment]
@oberon2007  last case. How about merge lastest changes in bumblebee code changes? Seems nobody review this... https://github.com/manjaro/packages-community/pull/267

Working for me like a charm. ;)

**Pull request merged**
